CREATE TABLE IF NOT EXISTS "music_rater_albums" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "music_rater_albums_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"music_rater_album_id" integer NOT NULL,
	"artist_name_raw" text NOT NULL,
	"album_title_raw" text NOT NULL,
	"artist_name_normalized" text NOT NULL,
	"album_title_normalized" text NOT NULL,
	"release_year" integer,
	"max_score_ratio" real,
	"dr_value" integer,
	"genre_slugs" jsonb,
	"source_sites" jsonb,
	"resolved_artist_mbid" text,
	"resolved_release_group_mbid" text,
	"resolved_at" timestamp with time zone,
	"synced_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
 IF NOT EXISTS (
  SELECT 1
  FROM pg_constraint
  WHERE conname = 'music_rater_albums_user_id_users_id_fk'
 ) THEN
  ALTER TABLE "music_rater_albums" ADD CONSTRAINT "music_rater_albums_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
 END IF;
END $$;
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "music_rater_albums_user_album_unique_idx" ON "music_rater_albums" USING btree ("user_id","music_rater_album_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "music_rater_albums_name_match_idx" ON "music_rater_albums" USING btree ("user_id","artist_name_normalized","album_title_normalized");
